# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Mac App Store command-line interface
brew "mas"
# GitHub command-line tool
brew "gh"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Non-interactive SSH password auth
brew "sshpass"

# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# File archiver
cask "keka"
# Web browser focusing on privacy
cask "brave-browser"
# Open-source code editor
cask "visual-studio-code"
# Mesh VPN based on WireGuard
cask "tailscale-app"

mas "Xcode", id: 497799835
mas "Wipr", id: 1662217862 
mas "Pages", id: 361309726
mas "Numbers", id: 361304891
mas "Keynote", id: 361285480
